package seeders

import (
	"invoice-system/internal/infra/db/models"
	"time"

	"gorm.io/gorm"
)

func SeedInvoices(db *gorm.DB) error {
	// ambil beberapa customer untuk variasi
	var customers []models.Customer
	if err := db.Find(&customers).Error; err != nil {
		return err
	}

	if len(customers) == 0 {
		return nil // tidak ada customer, skip seeding
	}

	now := time.Now()
	invoices := []models.Invoice{
		{
			InvoiceNumber: "INV-001",
			IssueDate:     now.AddDate(0, 0, -30),
			DueDate:       now.AddDate(0, 0, -16),
			Subject:       "Website Development Project",
			CustomerID:    customers[0].ID,
			TotalItems:    2,
			Subtotal:      4500000,
			Tax:           450000,
			TotalAmount:   4950000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -30),
			UpdatedAt:     now.AddDate(0, 0, -15),
		},
		{
			InvoiceNumber: "INV-002",
			IssueDate:     now.AddDate(0, 0, -28),
			DueDate:       now.AddDate(0, 0, -14),
			Subject:       "Mobile App Development",
			CustomerID:    customers[0].ID,
			TotalItems:    3,
			Subtotal:      7500000,
			Tax:           750000,
			TotalAmount:   8250000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -28),
			UpdatedAt:     now.AddDate(0, 0, -13),
		},
		{
			InvoiceNumber: "INV-003",
			IssueDate:     now.AddDate(0, 0, -25),
			DueDate:       now.AddDate(0, 0, -11),
			Subject:       "E-commerce Platform Setup",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    4,
			Subtotal:      12000000,
			Tax:           1200000,
			TotalAmount:   13200000,
			Status:        "unpaid",
			CreatedAt:     now.AddDate(0, 0, -25),
			UpdatedAt:     now.AddDate(0, 0, -25),
		},
		{
			InvoiceNumber: "INV-004",
			IssueDate:     now.AddDate(0, 0, -22),
			DueDate:       now.AddDate(0, 0, -8),
			Subject:       "Database Migration Services",
			CustomerID:    customers[0].ID,
			TotalItems:    1,
			Subtotal:      3000000,
			Tax:           300000,
			TotalAmount:   3300000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -22),
			UpdatedAt:     now.AddDate(0, 0, -7),
		},
		{
			InvoiceNumber: "INV-005",
			IssueDate:     now.AddDate(0, 0, -20),
			DueDate:       now.AddDate(0, 0, -6),
			Subject:       "API Development & Integration",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    2,
			Subtotal:      5500000,
			Tax:           550000,
			TotalAmount:   6050000,
			Status:        "unpaid",
			CreatedAt:     now.AddDate(0, 0, -20),
			UpdatedAt:     now.AddDate(0, 0, -20),
		},
		{
			InvoiceNumber: "INV-006",
			IssueDate:     now.AddDate(0, 0, -18),
			DueDate:       now.AddDate(0, 0, -4),
			Subject:       "UI/UX Design Services",
			CustomerID:    customers[0].ID,
			TotalItems:    3,
			Subtotal:      4200000,
			Tax:           420000,
			TotalAmount:   4620000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -18),
			UpdatedAt:     now.AddDate(0, 0, -3),
		},
		{
			InvoiceNumber: "INV-007",
			IssueDate:     now.AddDate(0, 0, -15),
			DueDate:       now.AddDate(0, 0, -1),
			Subject:       "Cloud Infrastructure Setup",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    2,
			Subtotal:      6800000,
			Tax:           680000,
			TotalAmount:   7480000,
			Status:        "unpaid",
			CreatedAt:     now.AddDate(0, 0, -15),
			UpdatedAt:     now.AddDate(0, 0, -15),
		},
		{
			InvoiceNumber: "INV-008",
			IssueDate:     now.AddDate(0, 0, -12),
			DueDate:       now.AddDate(0, 0, 2),
			Subject:       "SEO Optimization Package",
			CustomerID:    customers[0].ID,
			TotalItems:    1,
			Subtotal:      2500000,
			Tax:           250000,
			TotalAmount:   2750000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -12),
			UpdatedAt:     now.AddDate(0, 0, -12),
		},
		{
			InvoiceNumber: "INV-009",
			IssueDate:     now.AddDate(0, 0, -10),
			DueDate:       now.AddDate(0, 0, 4),
			Subject:       "Content Management System",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    3,
			Subtotal:      8200000,
			Tax:           820000,
			TotalAmount:   9020000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -10),
			UpdatedAt:     now.AddDate(0, 0, -10),
		},
		{
			InvoiceNumber: "INV-010",
			IssueDate:     now.AddDate(0, 0, -8),
			DueDate:       now.AddDate(0, 0, 6),
			Subject:       "Security Audit & Penetration Testing",
			CustomerID:    customers[0].ID,
			TotalItems:    2,
			Subtotal:      9500000,
			Tax:           950000,
			TotalAmount:   10450000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -8),
			UpdatedAt:     now.AddDate(0, 0, -8),
		},
		{
			InvoiceNumber: "INV-011",
			IssueDate:     now.AddDate(0, 0, -6),
			DueDate:       now.AddDate(0, 0, 8),
			Subject:       "Data Analytics Dashboard",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    4,
			Subtotal:      11200000,
			Tax:           1120000,
			TotalAmount:   12320000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -6),
			UpdatedAt:     now.AddDate(0, 0, -6),
		},
		{
			InvoiceNumber: "INV-012",
			IssueDate:     now.AddDate(0, 0, -4),
			DueDate:       now.AddDate(0, 0, 10),
			Subject:       "DevOps Implementation",
			CustomerID:    customers[0].ID,
			TotalItems:    2,
			Subtotal:      6700000,
			Tax:           670000,
			TotalAmount:   7370000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -4),
			UpdatedAt:     now.AddDate(0, 0, -4),
		},
		{
			InvoiceNumber: "INV-013",
			IssueDate:     now.AddDate(0, 0, -2),
			DueDate:       now.AddDate(0, 0, 12),
			Subject:       "Progressive Web App Development",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    3,
			Subtotal:      8900000,
			Tax:           890000,
			TotalAmount:   9790000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -2),
			UpdatedAt:     now.AddDate(0, 0, -2),
		},
		{
			InvoiceNumber: "INV-014",
			IssueDate:     now,
			DueDate:       now.AddDate(0, 0, 14),
			Subject:       "Machine Learning Model Development",
			CustomerID:    customers[0].ID,
			TotalItems:    2,
			Subtotal:      15000000,
			Tax:           1500000,
			TotalAmount:   16500000,
			Status:        "paid",
			CreatedAt:     now,
			UpdatedAt:     now,
		},
		{
			InvoiceNumber: "INV-015",
			IssueDate:     now.AddDate(0, 0, -35),
			DueDate:       now.AddDate(0, 0, -21),
			Subject:       "Legacy System Modernization",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    5,
			Subtotal:      22000000,
			Tax:           2200000,
			TotalAmount:   24200000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -35),
			UpdatedAt:     now.AddDate(0, 0, -20),
		},
		{
			InvoiceNumber: "INV-016",
			IssueDate:     now.AddDate(0, 0, -32),
			DueDate:       now.AddDate(0, 0, -18),
			Subject:       "Blockchain Integration Services",
			CustomerID:    customers[0].ID,
			TotalItems:    3,
			Subtotal:      18500000,
			Tax:           1850000,
			TotalAmount:   20350000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -32),
			UpdatedAt:     now.AddDate(0, 0, -17),
		},
		{
			InvoiceNumber: "INV-017",
			IssueDate:     now.AddDate(0, 0, -29),
			DueDate:       now.AddDate(0, 0, -15),
			Subject:       "IoT Platform Development",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    4,
			Subtotal:      13800000,
			Tax:           1380000,
			TotalAmount:   15180000,
			Status:        "unpaid",
			CreatedAt:     now.AddDate(0, 0, -29),
			UpdatedAt:     now.AddDate(0, 0, -29),
		},
		{
			InvoiceNumber: "INV-018",
			IssueDate:     now.AddDate(0, 0, -26),
			DueDate:       now.AddDate(0, 0, -12),
			Subject:       "Microservices Architecture",
			CustomerID:    customers[0].ID,
			TotalItems:    3,
			Subtotal:      10500000,
			Tax:           1050000,
			TotalAmount:   11550000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -26),
			UpdatedAt:     now.AddDate(0, 0, -11),
		},
		{
			InvoiceNumber: "INV-019",
			IssueDate:     now.AddDate(0, 0, -23),
			DueDate:       now.AddDate(0, 0, -9),
			Subject:       "Performance Optimization",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    2,
			Subtotal:      4800000,
			Tax:           480000,
			TotalAmount:   5280000,
			Status:        "unpaid",
			CreatedAt:     now.AddDate(0, 0, -23),
			UpdatedAt:     now.AddDate(0, 0, -23),
		},
		{
			InvoiceNumber: "INV-020",
			IssueDate:     now.AddDate(0, 0, -19),
			DueDate:       now.AddDate(0, 0, -5),
			Subject:       "Quality Assurance Testing",
			CustomerID:    customers[0].ID,
			TotalItems:    2,
			Subtotal:      3600000,
			Tax:           360000,
			TotalAmount:   3960000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -19),
			UpdatedAt:     now.AddDate(0, 0, -4),
		},
		{
			InvoiceNumber: "INV-021",
			IssueDate:     now.AddDate(0, 0, -16),
			DueDate:       now.AddDate(0, 0, -2),
			Subject:       "Digital Marketing Automation",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    3,
			Subtotal:      7200000,
			Tax:           720000,
			TotalAmount:   7920000,
			Status:        "unpaid",
			CreatedAt:     now.AddDate(0, 0, -16),
			UpdatedAt:     now.AddDate(0, 0, -16),
		},
		{
			InvoiceNumber: "INV-022",
			IssueDate:     now.AddDate(0, 0, -13),
			DueDate:       now.AddDate(0, 0, 1),
			Subject:       "Real-time Chat System",
			CustomerID:    customers[0].ID,
			TotalItems:    2,
			Subtotal:      5800000,
			Tax:           580000,
			TotalAmount:   6380000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -13),
			UpdatedAt:     now.AddDate(0, 0, -13),
		},
		{
			InvoiceNumber: "INV-023",
			IssueDate:     now.AddDate(0, 0, -11),
			DueDate:       now.AddDate(0, 0, 3),
			Subject:       "Video Streaming Platform",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    4,
			Subtotal:      16800000,
			Tax:           1680000,
			TotalAmount:   18480000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -11),
			UpdatedAt:     now.AddDate(0, 0, -11),
		},
		{
			InvoiceNumber: "INV-024",
			IssueDate:     now.AddDate(0, 0, -9),
			DueDate:       now.AddDate(0, 0, 5),
			Subject:       "Document Management System",
			CustomerID:    customers[0].ID,
			TotalItems:    3,
			Subtotal:      9200000,
			Tax:           920000,
			TotalAmount:   10120000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -9),
			UpdatedAt:     now.AddDate(0, 0, -9),
		},
		{
			InvoiceNumber: "INV-025",
			IssueDate:     now.AddDate(0, 0, -7),
			DueDate:       now.AddDate(0, 0, 7),
			Subject:       "Payment Gateway Integration",
			CustomerID:    customers[len(customers)-1].ID,
			TotalItems:    2,
			Subtotal:      4400000,
			Tax:           440000,
			TotalAmount:   4840000,
			Status:        "paid",
			CreatedAt:     now.AddDate(0, 0, -7),
			UpdatedAt:     now.AddDate(0, 0, -7),
		},
	}

	for _, inv := range invoices {
		var existing models.Invoice
		if err := db.Where("invoice_number = ?", inv.InvoiceNumber).First(&existing).Error; err != nil {
			if err == gorm.ErrRecordNotFound {
				if err := db.Create(&inv).Error; err != nil {
					return err
				}
			} else {
				return err
			}
		}
	}

	return nil
}
